### ISSUE TITLE
Bug: Footer is irresponsive and the logo in footer is distorted

### ISSUE THREAD

**Issue by SandeshGC** [gdscsmit/gdscsmit.github.io#102]
### What happened?

The footer looks good in mobile devices and large screens, but its contents overlap in medium sized screens.
- The logo of GDSC is also distorted due to unmatched height and width ratio. I would like to change the height to auto so that the ratio is maintained.

I will also work on other small things like centering the social media icons on their gray background, relocating the copyright message, etc.

Please kindly assign this to me.

### Add screenshots

Chrome:
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/59115123/36d6cc71-7358-472c-886e-ddeb72b01456)

Firefox:
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/59115123/1304e327-55b3-4c37-b736-9cdabc3738e9)

Chrome:
- current logo in footer:

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/59115123/76eeca83-71f9-489e-8829-5c62f260b0c1)

- proposed change:
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/59115123/f7980303-6fa1-410c-88ca-11331168ff29)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by pooranjoyb** [comment]
Go work on it! 🚀 @SandeshGC
