### ISSUE TITLE
Enhancing the UI of the site and making some section reponsive

### ISSUE THREAD

**Issue by rutikgagare** [gdscsmit/gdscsmit.github.io#11]
The contact form is not looking good in mobile phones 
![WhatsApp Image 2023-10-12 at 1 35 59 PM](https://github.com/gdscsmit/gdscsmit.github.io/assets/85502114/3de5c0b1-9fde-4abb-8593-072e56ee1cad)

The video is not responsive in mobile phone 
![WhatsApp Image 2023-10-12 at 1 35 58 PM](https://github.com/gdscsmit/gdscsmit.github.io/assets/85502114/2d0bc6f8-a499-48fd-acac-ce2bb613b7ec)

@girish0120 please assign it to me I am excited to work on this issue.

**Comment by pooranjoyb** [comment]
Yup Go for it! 🚀 @rutikgagare
