### ISSUE TITLE
[Improvement] Navbar is not looking so good.

### ISSUE THREAD

**Issue by Babunshil** [gdscsmit/gdscsmit.github.io#12]
*Chnages*
 - Increase the height
 - Correct the allignment
 - Addding hover effect to improve UI

> After
![Screenshot (128)](https://github.com/gdscsmit/gdscsmit.github.io/assets/106283743/bd82e724-dec5-4e0c-8ae8-1402d7916942)
> Before
![Screenshot (127)](https://github.com/gdscsmit/gdscsmit.github.io/assets/106283743/ea7a389a-e121-4fe3-8efa-c4e495aa2675)

**Comment by Babunshil** [comment]
@pooranjoyb I want to work on this. Can you please assign me it under Hacktoberfest-2023.

**Comment by pooranjoyb** [comment]
> @pooranjoyb I want to work on this. Can you please assign me it under Hacktoberfest-2023.

Go for it @Babunshil :rocket:
Make sure you add transitions too👍

**Comment by Babunshil** [comment]
@pooranjoyb  What about this hover effect on the nav links or previous on was better ?

![Screenshot (129)](https://github.com/gdscsmit/gdscsmit.github.io/assets/106283743/3ab93e7b-85db-4d52-a9ed-af7f4e4177e4)

**Comment by Babunshil** [comment]
https://github.com/gdscsmit/gdscsmit.github.io/assets/106283743/e9bf9605-0bf7-4210-963c-05bef72c8975

**Comment by pooranjoyb** [comment]
> 
> https://github.com/gdscsmit/gdscsmit.github.io/assets/106283743/e9bf9605-0bf7-4210-963c-05bef72c8975
> 
> 

Ya, it's fine but make sure that animation is not circular but only displays as an underline animation.
Also add the previous `frosted-glass` feature. 
The css for the same is already written, just add the class in the `Navbar`
@Babunshil
