### ISSUE TITLE
adding a dark mode to the website

### ISSUE THREAD

**Issue by piyushkdas0611** [gdscsmit/gdscsmit.github.io#15]
Well to solve the issue of eye straining of developers, i would like to add this feature

**Comment by pooranjoyb** [comment]
Thanks for raising an issue @piyushkdas0611 
But as of now, we're focusing on working out with the initial UI. 
We'll come to darkmode ASAP in the coming weeks. Hope you understand.

**Comment by piyushkdas0611** [comment]
sure no problem
