### ISSUE TITLE
Update Core Team Member Section

### ISSUE THREAD

**Issue by gdscsmit** [gdscsmit/gdscsmit.github.io#2]
### Tasks : 
- Create different sections for different domain core members
- You can either use Lists of names or
- Suggest some better UI for the same

**Comment by Nwakaego-Ego** [comment]
Hi, 

Please elaborate on this issue or add context to it, i will love to work on it.

Thank you.

**Comment by Tusharrgrg** [comment]
hey, i want to work on this issue can you assign me this issue.

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !!

THANKS for your consideration.

**Comment by sayumimuthu** [comment]
Hi, I'd like to contribute to this issue. Would you be able to assign it to me?

**Comment by Tusharrgrg** [comment]
hello @pooranjoyb can i add external css to enhance code readability and improve development efficiency?.

**Comment by pooranjoyb** [comment]
Hey @sayumimuthu & @Niraj-1729 
Appreciating your interest in contributing to the repository, but as of now 2 peeps are already assigned to this issue. 
You guys can create additional issues, find some bugs, make UI changes and start working on them. I'll surely assign them.

**Comment by pooranjoyb** [comment]
> Hello @pooranjoyb, how can I get in touch with you?

Checkout my profile, you can mail or drop a text in discord :)
