### ISSUE TITLE
Add dynamic year copyright in the footer

### ISSUE THREAD

**Issue by rhnas110** [gdscsmit/gdscsmit.github.io#20]
### Issue Description
Currently I saw the code in the footer of the website for the copyright year is still static, I want to add a dynamic year copyright in the footer of the website.

### Describe the solution you'd like.
I create a new variable to get dynamic year info, named const currentYear and i called the variable with JSX.

### Screenshots
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/51848196/8ddaf668-da9c-444b-9a0b-26d5efa72ca0)

### Additional information
Can you take my advice and assign this task to me Sir @gdscsmit ? and I am new to open source contributions and I would love to contribute to your project! I also participated in Hacktoberfest2023.

**Comment by pooranjoyb** [comment]
Nice idea! Go for it @rhnas110 🚀
