### ISSUE TITLE
when ever user link on the log of GDSC it scroll to up to front.

### ISSUE THREAD

**Issue by Sushilverma002** [gdscsmit/gdscsmit.github.io#22]
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/114687502/6e3fb84b-6c5e-4b80-b0fb-7119cda594ad)

1. when user click on logo it came upwards .

**Comment by pooranjoyb** [comment]
Please elaborate the issue. Did you mean something like the `scroll to top` sort of button?
@Sushilverma002

**Comment by Sushilverma002** [comment]
NO ,when you click on log and it doesn't matter in which part of page you are YOU WILL CAME BACK TO front.

**Comment by pooranjoyb** [comment]
I'd say, better create a `scroll-to-top` button that pops up on the `bottom right corner` of the page
It should appear on 50% scrolling of the page, else it should be hidden.
@Sushilverma002

**Comment by pooranjoyb** [comment]
Update @Sushilverma002 ?

**Comment by Sushilverma002** [comment]
in progress @pooranjoyb

**Comment by Sushilverma002** [comment]
https://github.com/gdscsmit/gdscsmit.github.io/assets/114687502/29fc5b88-886e-48e4-a901-86ae57dffcfb

@pooranjoyb have a lookk !!!!! and please confirm so that i proceed to make pr.

**Comment by pooranjoyb** [comment]
Yup, you're good to go! @Sushilverma002

**Comment by Sushilverma002** [comment]
ohh nice to hear.
