### ISSUE TITLE
Add navbar logo link and UI changes

### ISSUE THREAD

**Issue by avg77** [gdscsmit/gdscsmit.github.io#24]
Hey there @pooranjoyb!
I intend to link the home page to the navbar logo.
Secondly, i want to make some small UI changes to buttons size and give the text a 'card' look.

Attached screenshots show the changes

1) Before:-
![bf1](https://github.com/gdscsmit/gdscsmit.github.io/assets/91598955/1e8ae85a-2cc5-400b-916d-545d34e1e8fa)

2) After:-
![af1](https://github.com/gdscsmit/gdscsmit.github.io/assets/91598955/8e2ca54f-8791-4fb7-a33e-69ef8192c9f3)

I'm ready to discuss and incorporate changes as per your requirements.
Kindly assign me this issue under appropriate tags.

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @avg77
