### ISSUE TITLE
Add a Preloader for the Website

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#25]
### Tasks : 
- Find `loader.gif` in `./public/` directory,
- Either convert it to `Transparent gif` or use the same for creating a `preloader` for the website.
- The loader should be in the center of the page.
- Make sure it's responsive

#### ⚠️ NOTE : Remove the `Redirecting...` text from `/app` route and add the `preloader` there too. 
Click [here](https://stackabuse.com/how-to-create-a-loading-animation-in-react-from-scratch/) for reference.

**Comment by arnabpal2022** [comment]
Can I work on this Issue @pooranjoyb?

**Comment by Petsamuel** [comment]
assign this task to me

**Comment by pooranjoyb** [comment]
Update @Petsamuel & @arnabpal2022 ?

**Comment by Petsamuel** [comment]
@pooranjoyb I'll make a pull request right away... never knew it was still open

**Comment by Petsamuel** [comment]
@pooranjoyb here is how is looks like: https://jyp9lq-5173.csb.app/
