### ISSUE TITLE
Adding transition delay when hovering over navbar and 4 sub domains of the vision section.

### ISSUE THREAD

**Issue by RonitBaranwal** [gdscsmit/gdscsmit.github.io#27]
It is an absolutely marvelous website. But the thing which I want to work on is to add some transition effects on the navbar elements like Home, Contact they are very fast and it feels almost like a random display. Similar for the Vision section .

I would like to add transition delays and make the user experience better.

If its okay for you can I work on this issue ?

**Comment by pooranjoyb** [comment]
Go for it 🚀 @RonitBaranwal

**Comment by RonitBaranwal** [comment]
I don't why the development server mentioned in the README.md file is not working for http://localhost:3000/  i.e refusing to connect .
And the local server which I am getting from vite is just showing me the favicon with a blank page and no-content.

**Comment by pooranjoyb** [comment]
Oppsie, i guess it's a typo in the `README.md` file.
The website will start at `localhost:5173`
And regarding the blank screen, mane sure you installed the dependencies by running `npm run dev` in the root dir. @RonitBaranwal

**Comment by RonitBaranwal** [comment]
I did run the commands of npm install .
But after npm run dev I am getting this page 


![Screenshot 2023-10-15 150743](https://github.com/gdscsmit/gdscsmit.github.io/assets/123174522/7ee131fe-873e-4474-97bf-2192ddbe24f8)

**Comment by pooranjoyb** [comment]
Check the console. you can also DM me in discord. @RonitBaranwal 
You can join using this [link](https://discord.gg/B7TB5wR9)

**Comment by sid86-dev** [comment]
Create a  `.env` file in the Root directory, then add the `VITE_FIREBASE_DATABASE_URL` as mentioned in the `README.md` file.
