### ISSUE TITLE
Add a footer for the website

### ISSUE THREAD

**Issue by pranavsuriya-sr** [gdscsmit/gdscsmit.github.io#29]
Add a footer for the website with links, social media icons and an about section.

**Comment by pooranjoyb** [comment]
Go for it! @pranavsuriya-sr 🚀

**Comment by therefat** [comment]
assign me

**Comment by falgun143** [comment]
@pooranjoyb would like to work on it and will create a good footer section.

**Comment by pooranjoyb** [comment]
Go for it @falgun143 🚀
