### ISSUE TITLE
Use Firebase RTDB for Contact Us page 📃 

### ISSUE THREAD

**Issue by gdscsmit** [gdscsmit/gdscsmit.github.io#3]
### Tasks : 
- Initiate `Firebase Real Time Database` and save all form submissions to DB
- Make sure to display a `modal` on successful submission of the form
- Create `.env` for storing `Firebase Secrets`

**Comment by GD0910** [comment]
HI . I am new with firebase so can you explain what all is required

**Comment by GD0910** [comment]
ok can you assign me this issue .Will try to solve this

**Comment by GD0910** [comment]
@pooranjoyb I faced an issue after running `npm run build` .I have messaged you in discord

**Comment by sayumimuthu** [comment]
Hi, I'd like to contribute to this issue. Would you be able to assign it to me?

**Comment by GD0910** [comment]
> Hi, I'd like to contribute to this issue. Would you be able to assign it to me?

I’m working on it
