### ISSUE TITLE
Shadow Bug in cards

### ISSUE THREAD

**Issue by dalvishruti14** [gdscsmit/gdscsmit.github.io#31]
Kindly assign this issue to me. I would like to work on it.
![gdsc](https://github.com/gdscsmit/gdscsmit.github.io/assets/120911455/39275105-ecd6-42d9-932f-2e57cf04b1d1)

**Comment by pooranjoyb** [comment]
Nice catch! Go for it! 🚀 @dalvishruti14

**Comment by dalvishruti14** [comment]
This issue is already resolved in the updated file

**Comment by pooranjoyb** [comment]
Hey @dalvishruti14 
It is to let you know that someone just fixed that issue before you. But don't worry, our repository has plenty of bugs and vulnerabilities to fix!
#### Here is another one for you.
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/577f152a-e35f-4ef7-959c-f0e1db63059f)
#### Could you please fix this shadow issue?

**Comment by dalvishruti14** [comment]
Yes will do
