### ISSUE TITLE
Add fade-in animations to vision cards

### ISSUE THREAD

**Issue by Petrosdevri** [gdscsmit/gdscsmit.github.io#32]
I would like to add fade-in animations to Vision cards because it would improve the user experience in my opinion (it intrigues the user to see what is next and would offer a smooth appearance combination in parallel with the card shadows).

I also believe we could apply such animations to the rest of the website content but if you do not like it I will only alter the `Vision` section.

**Comment by pooranjoyb** [comment]
Yes, that really sounds appealing. Could you add `framer-motion` for the `Vision` section?
Or are you planning something else?
@Petrosdevri

**Comment by Petrosdevri** [comment]
Yes I could try doing that.

**Comment by falgun143** [comment]
@Petrosdevri 
Would love to work on this.
Please assign it to me.

**Comment by falgun143** [comment]
Please review my pr #40
