### ISSUE TITLE
Adding hyperlinks to the Lead's (Aryan Lohia) social media icons in teams page.

### ISSUE THREAD

**Issue by ch-sohan** [gdscsmit/gdscsmit.github.io#35]
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/108716877/94acec85-9a1a-4a00-afc0-0a8443d98f20)
I would like to add hyperlinks to the Lead (Aryan Lohia) to the social media icons and I will add his profile picture too. Please assign me this task under hactoberfest23. Thank you.

**Comment by pooranjoyb** [comment]
Hey @ch-sohan , Please check the branch `teamsv1`
We are working on the teams page. 
This issue has already been completed. @ch-sohan
