### ISSUE TITLE
Fix Hamburger Menu in smaller screens ⚠️ 

### ISSUE THREAD

**Issue by gdscsmit** [gdscsmit/gdscsmit.github.io#4]
### Tasks : 
- Navbar doesn't closes after opening in the smaller screens
- Make sure that Navbar remains responsive after fixing the bug
- Fix the Bug

**Comment by nitinryali** [comment]
Assign this

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @nitinryali

**Comment by nitinryali** [comment]
Created the PR review it
