### ISSUE TITLE
Use SSG to fix poor First Contentful Paint

### ISSUE THREAD

**Issue by sid86-dev** [gdscsmit/gdscsmit.github.io#41]
### Implementing Static Site Generation `(SSG)` for optimized performance. This approach will prioritize the delivery of static content, allowing ample time to load static data and APIs efficiently.

**Comment by pooranjoyb** [comment]
Please elaborate the changes that you wish to create @sid86-dev

**Comment by sid86-dev** [comment]
### After running the lighthouse audit the report are as follows:

<img width="450" src="https://pdfgo.s3.ap-south-1.amazonaws.com/Screenshot+2023-10-15+at+8.01.28%E2%80%AFPM.png" alt="audit-report" >


### Two Approaches to Address this Issue:
- One solution is to leverage **plugins** like `Gatsby` or consider migrating to the `next.js` framework. This move promises not only to resolve the problem but also to significantly enhance performance and provide support for `PWA`.

### Balancing Priorities:
- It's essential to weigh the significance of this issue at the current development stage. Moreover, it could serve as an exciting opportunity for beginners eager to contribute to this repository. Every challenge is an invitation to a new chapter in their learning journey.

### A Valuable Suggestion for Sustainable Growth:
- Here's a small yet significant suggestion for best practices and sustainable scaling: Just a reminder for this project's continuous evolution. :rocket:

**Comment by pooranjoyb** [comment]
To answer your suggestions : 
- Migration to `next.js` at this stage is not possible.
- What changes are to be made for leverage `Gatsby` plugins? Pen down the cons.

@sid86-dev
