### ISSUE TITLE
[Bug] Contact Form Image shrinks in smaller screens

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#43]
### Tasks : 
- Align the image properly and fix it's responsiveness.

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/aa31c812-ddef-47af-b6cf-0e82c86386af)

**Comment by dalvishruti14** [comment]
Kindly assign this issue to me.

**Comment by vivekmahindrakar** [comment]
can you give me the endpoint/url of the form?
