### ISSUE TITLE
add Dependabot

### ISSUE THREAD

**Issue by Akshayp02** [gdscsmit/gdscsmit.github.io#46]
To add Dependabot to a project, create a dependabot.yml file in project root. Configure it to check for updates in project's dependencies, and set up notifications for automated pull requests. Dependabot will then help keep dependencies up-to-date, enhancing project stability and security.

**Comment by pooranjoyb** [comment]
Please elaborate the functionalities that our bot will be providing :) @Akshayp02

**Comment by Akshayp02** [comment]
Dependabot is a tool commonly used in React projects to automate dependency management. It scans a project's package.json file, identifying outdated or vulnerable dependencies (such as React libraries, plugins, or other packages). Dependabot then automatically creates pull requests to update these dependencies to their latest versions. This is crucial for several reasons:

- Security: It helps identify and resolve vulnerabilities, reducing the risk of security breaches.

- Stability: Keeping dependencies up-to-date ensures that a project remains stable and compatible with the latest features and 
   bug fixes.

- Efficiency: Manual dependency updates can be time-consuming, but Dependabot automates this process, saving developers 
  time.

- Best Practices: Regular updates align with best practices for maintaining React projects, improving code quality and 
    performance.

**Comment by pooranjoyb** [comment]
Okay, just one last question, sometimes it happens that some features become deprecated in newer versions, could we also tackle that?

**Comment by Akshayp02** [comment]
Dependabot helps maintain software dependencies by automatically updating them to the latest versions, ensuring security and compatibility. While it addresses vulnerabilities and compatibility, it may not address deprecated features, which developers must handle manually by updating their code to use alternative approaches in newer dependencies.

**Comment by pooranjoyb** [comment]
Okaay, Go for it! @Akshayp02 🚀
