### ISSUE TITLE
Reserved characters in HTML must be replaced with entities:

### ISSUE THREAD

**Issue by sid86-dev** [gdscsmit/gdscsmit.github.io#51]
Some characters are reserved in HTML.

If you use the less than (<) or greater than (>) signs in your HTML text, the browser might mix them with tags. Entity names or entity numbers can be used to display reserved HTML characters.

Entity names look like this:

| Entity   | Description                     | Entity  | Description               |
|----------|---------------------------------|---------|---------------------------|
| `&lt;`   | Less than (<)                   | `&gt;`  | Greater than (>)          |
| `&amp;`  | Ampersand (&)                   | `&copy;` | Copyright (©)              |
| `&nbsp;` | Non-breaking space ( )          | `&mdash;` | Em dash (—)                |
| `&ldquo;` | Left double quotation mark (“) | `&rdquo;` | Right double quotation mark (”) |
| `&copy;` | Copyright symbol (©)           | `&reg;`  | Registered trademark symbol (®) |
| `&trade;` | Trademark symbol (™)          | `&sect;` | Section symbol (§)         |

**Comment by pooranjoyb** [comment]
Please mention the changes that you're going to make in our website. @sid86-dev

**Comment by sid86-dev** [comment]
* To replace all the reserved keywords to HTML entities.

**Comment by pooranjoyb** [comment]
Okay, go for it! @sid86-dev
