### ISSUE TITLE
Create a Modal for Contact Form Submission ✉️ 

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#56]
### Tasks : 
- Create a Modal for `Contact` form submission
- This Modal should pop up with a message saying that `Message successfully Sent`
- Also add a `X` button to close the Modal, after it pops up
- **Responsiveness is PRIORITY**

**Comment by imshaaz21** [comment]
@pooranjoyb  Could you please assign me this issue?

**Comment by pooranjoyb** [comment]
Go for it! I'll assign u :rocket: @imshaaz21
