### ISSUE TITLE
Twitter logo needs to be updated to X

### ISSUE THREAD

**Issue by adi-ray** [gdscsmit/gdscsmit.github.io#61]
Since twitter's logo has been changed . So, I would like to update the logo in socials of every team members.

Before :
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/96347576/d4513dc3-be9d-4273-b575-dbd48317baf9)

After:
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/96347576/2f8abc06-4acd-470d-9039-71457de0a166)

**Comment by pooranjoyb** [comment]
Go for it @adi-ray
