### ISSUE TITLE
Contact Page image should be changed to official image

### ISSUE THREAD

**Issue by Suhaani07** [gdscsmit/gdscsmit.github.io#65]
<img width="1065" alt="image" src="https://github.com/gdscsmit/gdscsmit.github.io/assets/98284331/be886dbb-6ff5-4928-bc73-e159f534a913">
This should be updated to official GDSC logo. Kindly assign me this under hacktoberfest 2023

**Comment by pooranjoyb** [comment]
Okay go for it! @Suhaani07
