### ISSUE TITLE
Create a workflow that deploys a preview in the `gh-pages`

### ISSUE THREAD

**Issue by MrPurushotam** [gdscsmit/gdscsmit.github.io#7]
Hy if you could link the GitHub repository with Netlify or something else then contributors might find it easy to report new issues and also it will get easy for them to judge the issue and whether they can make meaningful contribution or not.

**Comment by pooranjoyb** [comment]
Yeah, Seems Kinda Important. 
But I'd suggest that as we're already hosted in `gh-pages` so, it'd be better if we can create a workflow that deploys a preview in the `gh-pages` itself.
Lemme know if that's feasible?
@MrPurushotam

**Comment by sid86-dev** [comment]
> Yeah, Seems Kinda Important. But I'd suggest that as we're already hosted in `gh-pages` so, it'd be better if we can create a workflow that deploys a preview in the `gh-pages` itself. Lemme know if that's feasible? @MrPurushotam

Certainly, it's absolutely possible through the help of GitHub workflows. Please assign me this issue, and I'll promptly submit my pull request.
