### ISSUE TITLE
Create a New Component for Projects 🚀 

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#71]
## Tasks : 
- Create an interactive UI displaying the projects by GDSC SMIT
- The component should display all the open source projects, it's description and maintainers.
- The project cards should redirect to official Github of GDSC-SMIT
- Component should be rendered on clicking this : 
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/aa1f195c-7cf2-44c3-8ea3-0d94d88cc2f9)

#### Further improvements will be made in the upcoming issues.

**Comment by Chirag-Nanda** [comment]
Can I be assigned this issue?

**Comment by pooranjoyb** [comment]
> Can I be assigned this issue?

Go for it! 🚀

**Comment by falgun143** [comment]
@pooranjoyb  can u assign it to me last time there where merge conflicts this time i will ensure there are no conflicts

**Comment by pooranjoyb** [comment]
> @pooranjoyb  can u assign it to me last time there where merge conflicts this time i will ensure there are no conflicts
> 

Hey @falgun143 , this issue is already assigned. 
If there's no update by tomorrow 11am, I'll surely assign this to you. 
Till then please try to fix the merge-conflict of the PR you opened. Don't worry, I'll help you too. :smile:

**Comment by falgun143** [comment]
@pooranjoyb Please assign and also tell me exactly what to do .When i click on the project component should i redirect to  official Github of GDSC-SMIT or should i redirect to other component which gives me the  projects by GDSC SMIT.If it should redirect to new page which will have projects of gdsc smit ,Then which projects to show.

**Comment by 22Yash** [comment]
@pooranjoyb can you assigned to me . We have to create a card with button which on click redirect to GDSC-SMIT GitHub page .

**Comment by pooranjoyb** [comment]
> @pooranjoyb Please assign and also tell me exactly what to do .When i click on the project component should i redirect to official Github of GDSC-SMIT or should i redirect to other component which gives me the projects by GDSC SMIT.If it should redirect to new page which will have projects of gdsc smit ,Then which projects to show.

You should redirect to a component
- This component will contain some cards
- Each card will represent information about the Project by GDSC-SMIT.
- On clicking a Specific project, the user should redirect to the Official Github Repo of the same.

@falgun143

**Comment by pooranjoyb** [comment]
Update @falgun143 ?

**Comment by falgun143** [comment]
@pooranjoyb will give u update by today night 11.

**Comment by 0xSahilx** [comment]
Hey @pooranjoyb , I was working on this issue and had almost done with most of the stuff but I am facing a issue that i dont understard howw the imagegs are imported from firebase and even i dont have any access to your firebase . So should  i import some normal images right away into the code then?

**Comment by falgun143** [comment]
@pooranjoyb  iam done just some changes a will make pr.
