### ISSUE TITLE
Error 412 at `/team` route

### ISSUE THREAD

**Issue by sid86-dev** [gdscsmit/gdscsmit.github.io#73]
A required service account is missing necessary permissions. Please resolve by visiting the Storage page of the Firebase Console and re-linking your Firebase bucket or see this FAQ for more info: https://firebase.google.com/support/faq#storage-accounts. If you recently made changes to your service account, please wait a few minutes for the changes to propagate through our systems and try again.

**Comment by pooranjoyb** [comment]
Thanks for raising this issue @sid86-dev but we're restricting contributions to `Teams Page` as of now.
`/team` route has direct access to `Firebase Storage`, hence the access cannot be given as it has many delicate information.
