### ISSUE TITLE
[Mobile UI Responsive]<Blogs Section Is Not Responsive>

### ISSUE THREAD

**Issue by Ayusht777** [gdscsmit/gdscsmit.github.io#75]
Making Blogs section UI responsive for mobile devices

**Comment by pooranjoyb** [comment]
Could you provide me with Screenshots? @Ayusht777

**Comment by Ayusht777** [comment]
![Uploading Screen Shot 2023-10-18 at 19.32.01.png…]()

**Comment by pooranjoyb** [comment]
> ![Screen Shot 2023-10-18 at 19 32 01](https://github.com/gdscsmit/gdscsmit.github.io/assets/106388215/5e4c1ce9-ddda-455d-a7a2-c5b61853c4e1)
> 

Go for it!

**Comment by Emondrax007** [comment]
i want work on this issue.

**Comment by pooranjoyb** [comment]
> i want work on this issue.

Go for it! 🚀

**Comment by Ayusht777** [comment]
hey can you tell me who can work on this issue you have assigned both of us so please 
confirm it

**Comment by Ayusht777** [comment]
okay

**Comment by Ayusht777** [comment]
@Emondrax007  hey can you tell me you are working on it or not

**Comment by Ayusht777** [comment]
@pooranjoyb  hey just assigned this issue to me so i can work on it

**Comment by pooranjoyb** [comment]
> @pooranjoyb  hey just assigned this issue to me so i can work on it

Drop a PR by tomorrow. @Ayusht777

**Comment by Ayusht777** [comment]
okay i will do it

**Comment by Ayusht777** [comment]
hi i am getting this error 
**Error fetching files from storage: FirebaseError: Firebase Storage: Max retry time for operation exceeded, please try again. (storage/retry-limit-exceeded)**

also i added .env file in root directory but blog page is not working

**Comment by pooranjoyb** [comment]
@Ayusht777 Check contributing guidelines and readme.md

**Comment by Ayusht777** [comment]
hi check the guidelines and done all steps correct but i am getting api error 
Error fetching Blogger blogs: 
Object { stack: "AxiosError@http://localhost:5173/node_modules/.vite/deps/axios.js?v=22e14b80:375:18\nsettle@http://localhost:5173/node_modules/.vite/deps/axios.js?v=22e14b80:1193:12\nonloadend@http://localhost:5173/node_modules/.vite/deps/axios.js?v=22e14b80:1421:13\n", message: "Request failed with status code 400", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }

**Comment by pooranjoyb** [comment]
> hi i am getting this error **Error fetching files from storage: FirebaseError: Firebase Storage: Max retry time for operation exceeded, please try again. (storage/retry-limit-exceeded)**
> 
> also i added .env file in root directory but blog page is not working

Okay, if you're working on `/blogs` page, you'll have to add your own `Blogger API key` as an environment variable.

**Comment by Ayusht777** [comment]
so how to get the api key

**Comment by Ayusht777** [comment]
can you guide me

**Comment by pooranjoyb** [comment]
> can you guide me 

Okay, so you'll need a Blogger account for this.

- Find & Copy the `Blogger API key` of your account
- Then in the `.env` file create a variable called `VITE_API_KEY` and add your `API KEY` here.

Then you'll be able to see the Blogs page and it's content.

@Ayusht777

**Comment by Ayusht777** [comment]
and where i can create the blogger account

**Comment by pooranjoyb** [comment]
It's a `Blog Platform` where people write blogs. Search Google for `Blogger.com`
