### ISSUE TITLE
Improving the styling of the Vision cards

### ISSUE THREAD

**Issue by DannyK05** [gdscsmit/gdscsmit.github.io#8]
@gdscsmit @girish0120  Can I work on styling this vision and goal section.

![gdscmit](https://github.com/gdscsmit/gdscsmit.github.io/assets/105021997/848bef03-996c-4ffc-a48e-fa629031547f)

**Comment by pooranjoyb** [comment]
It would be great if you could you just drop a sample of the UI. 😄 
@DannyK05

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !!

THANKS for your consideration.

**Comment by DannyK05** [comment]
@pooranjoyb
I want to make them like a card UI. 
Something like this 👇

![IMG_20231012_080557.jpg](https://github.com/gdscsmit/gdscsmit.github.io/assets/105021997/22d2b10d-69dd-4bbb-9c53-e7c83af8296b)

I'll put a preview of it in the pull request so you know what I did.

**Comment by DannyK05** [comment]
I'll put suitable images for each heading or you can send images taken at your club that reflects the headings so I would include them.

**Comment by pooranjoyb** [comment]
> I'll put suitable images for each heading or you can send images taken at your club that reflects the headings so I would include them. 

Go for it and make sure it's responsive!

**Comment by DannyK05** [comment]
> > I'll put suitable images for each heading or you can send images taken at your club that reflects the headings so I would include them. 
> 
> Go for it and make sure it's responsive!

Yeah, I will

**Comment by shreyanshig** [comment]
Hi, Could you please assign this task to me?
