### ISSUE TITLE
Bug: Footer in `Contact` Page

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#84]
### Add screenshots

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/90945182/59e6da05-fb0c-4de4-98ad-ee80792c932d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Nupur19nj** [comment]
Hey can you please assign me this task under hacktober-accepted!

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @Nupur19nj

**Comment by manisha765** [comment]
Hey there!  Is this Issue still available for Solving , I Can help you out for this Project , So I Would like to get accepted to work upon this ! Please do Assign this task As soon as Possible !

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by Nupur19nj** [comment]
Hey! I completed the task kindly merge it,
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/114866308/ea32040c-1fa8-40fd-9861-1c5d158eb3c6)
