### ISSUE TITLE
Bug: Fix alignment of Social Icons

### ISSUE THREAD

**Issue by mdtausifiqbal** [gdscsmit/gdscsmit.github.io#86]
### What happened?

There is a misalignment in social icons.

### Add screenshots

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/33699526/f83d5940-6d52-495b-b1dd-b8d3f1e55778)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by pooranjoyb** [comment]
Please wait for an assignment before raising a PR @mdtausifiqbal

**Comment by Sou6161** [comment]
Hey! I want to work in this issue, is it open or closed ,if open please assign me
