### ISSUE TITLE
Docs: Update README.md file

### ISSUE THREAD

**Issue by WeiJian123-tech** [gdscsmit/gdscsmit.github.io#92]
### What you want to add in the documentation?

Hello! I noticed a typo with your [README.md](https://github.com/gdscsmit/gdscsmit.github.io/blob/main/README.md) under [Getting Started](https://github.com/gdscsmit/gdscsmit.github.io/#getting-started)? I tried cloning the repository with `git clone https://github.com/gdsc-organization/gdsc-website.git` however my terminal within VSCode threw an error stating that the repository was not found. When I tried `git clone https://github.com/gdscsmit/gdscsmit.github.io.git` given by GitHub's `<> Code` button, I was able to clone the repository. May I please update your [README.md](https://github.com/gdscsmit/gdscsmit.github.io/blob/main/README.md) to include the correct `git clone` link?

### Add screenshots

![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/55195954/ce5add27-770c-4000-914d-f10b5deee288)
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/55195954/4d37eb29-c88e-434a-8c53-51c3bda2f60e)
![image](https://github.com/gdscsmit/gdscsmit.github.io/assets/55195954/cae56199-c93c-4cf8-b096-6953304cf8c8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by pooranjoyb** [comment]
Go for it! 🚀 @WeiJian123-tech

**Comment by WeiJian123-tech** [comment]
Awesome! 😃 I'll make a pull request shortly.

**Comment by WeiJian123-tech** [comment]
I made my pull request just now. Feel free to give any feedback. 👍
