### ISSUE TITLE
Bug: Inconsistent Display of Text on Hover

### ISSUE THREAD

**Issue by Divjot02** [gdscsmit/gdscsmit.github.io#94]
### Description
When hovering over the icons in the footer, the current styling results in inconsistent and undesirable padding and layout for the displayed text. This affects the visual consistency and user experience of the website.

### Steps to Reproduce

1. Visit the website. (https://gdscsmit.github.io/)
2. Hover over the social media icons.

### Add screenshots

[Screencast from 21-10-23 06:12:44 PM IST.webm](https://github.com/gdscsmit/gdscsmit.github.io/assets/140320635/c969afc3-335c-445e-bfde-9938272ef644)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by pooranjoyb** [comment]
Okay, so this is actually fixed in the repository. But is yet to be deployed.
