### ISSUE TITLE
Style: Adding Components in `/projects` route

### ISSUE THREAD

**Issue by pooranjoyb** [gdscsmit/gdscsmit.github.io#95]
### Tasks : 

- Add the Navbar in the page.
- Add a Title or introduction similar to the `/teams` page.
- Add the Footer.
- Match the color scheme.
- RESPONSIVENESS IS PRIORITY

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @pooranjoyb  can you elaborate on this issue in detail?

**Comment by pooranjoyb** [comment]
> Hi @pooranjoyb  can you elaborate on this issue in detail?

Go for it! @Muhammad-Shahid-Jamal :rocket:

**Comment by pooranjoyb** [comment]
@Muhammad-Shahid-Jamal 

Components are already created and ready to be used. You'll just have to import them and put them in correct order making sure that the UI remains responsive.
Do lemme know if you face any issues. :)

**Comment by Muhammad-Shahid-Jamal** [comment]
ok, so I have to create a new route called ```/projects```? if it's correct kindly assign this issue to me so I can contribute to it Thanks

**Comment by pooranjoyb** [comment]
It's already there. Click on projects in the `Vision section` in Home Page. You'll be redirected.

**Comment by Muhammad-Shahid-Jamal** [comment]
@pooranjoyb ```/teams``` route is not loading I am getting these error on that page
<img width="1680" alt="Screenshot 2023-10-23 at 10 16 25 PM" src="https://github.com/gdscsmit/gdscsmit.github.io/assets/26340344/b77332c6-eafd-4aaa-b309-537564f94b6f">

**Comment by Muhammad-Shahid-Jamal** [comment]
@pooranjoyb  i have to check what components need to show on ```/projects``` route.

**Comment by Muhammad-Shahid-Jamal** [comment]
<img width="1680" alt="Screenshot 2023-10-23 at 10 51 29 PM" src="https://github.com/gdscsmit/gdscsmit.github.io/assets/26340344/39109829-7656-4bc2-8144-3b99b9080db9">
check project route is that correct? and let me know what text have to be replaced with teams text

**Comment by pooranjoyb** [comment]
> <img alt="Screenshot 2023-10-23 at 10 51 29 PM" width="1680" src="https://user-images.githubusercontent.com/26340344/277427752-39109829-7656-4bc2-8144-3b99b9080db9.png"> check project route is that correct? and let me know what text have to be replaced with teams text

This is Good. Nice work @Muhammad-Shahid-Jamal

**Comment by Muhammad-Shahid-Jamal** [comment]
@pooranjoyb plz merge my Pull request to see these changes
